### ISSUE TITLE
What's status of this repository?

### ISSUE THREAD

**Issue by farooqkz** [Bear-03/vosk-rs#7]
Hello. Since the last update was 2 years ago, may I ask if this project is abandoned or what?

**Comment by Bear-03** [comment]
Nope not abandoned at all! It's just that there haven't been any new additions to Vosk since I started the project (I check periodically but I haven't noticed anything new)

**Comment by Bear-03** [comment]
Same for PRs and issues, no one has reported anything so there isn't a reason to update or commit new code. It's a fairly simple wrapper so it makes sense that there isn't much to fix

**Comment by farooqkz** [comment]
So it's still usable. Great! And thank you for your quick reply :)

**Comment by Bear-03** [comment]
> So it's still usable. Great! And thank you for your quick reply :)

No worries! Yes, it's working just like the first day. I still use it in some projects of mine :D
